#!/bin/bash

echo -e "\n\t\tHello CapFalc"

echo -e "\nMove sources to target directory /var/www"
cp -rf /var/www-bak/* /var/www/
rm -rf /var/www-bak 
echo -e "\nComposer Install"
cd /var/www && composer install
echo -e "\nComposer Update"
cd /var/www && composer update
echo -e "\nLaunch previous entrypoint"
docker-php-entrypoint
echo -e "\nLaunch apache"
apache2-foreground
