#!/bin/bash

echo -e "\nCheck Sources"
CONTENT=$(ls -l /var/www | wc -l)
echo "CONTENT(${CONTENT})"
if [ "${CONTENT}" -lt 4 ]; then
    echo -e "\nMove sources to target directory /var/www"
    cp -rf /var/www-bak/* /var/www/
fi

echo -e "\nComposer Install"
cd /var/www && composer install -q

echo -e "\nComposer Update"
cd /var/www && composer update -q

echo -e "\nLaunch previous entrypoint"
docker-php-entrypoint

echo -e "\nApply Drupal updates"
/var/www/vendor/drush/drush/drush cr -y
/var/www/vendor/drush/drush/drush updb -y
/var/www/vendor/drush/drush/drush cr -y
/var/www/vendor/drush/drush/drush cim -y
/var/www/vendor/drush/drush/drush cr -y

echo -e "\nLaunch apache"
apache2-foreground
