#!/bin/bash

echo -e "\n\t\tHello CapFalc"

cat /etc/apache2/sites-available/000-default.conf
cat /etc/apache2/sites-available/default-ssl.conf 
cat /etc/apache2/ports.conf

CONTENT=$(find . -printf x | wc -c)
if [ ! "$CONTENT" -gt 3 ]; then
    echo -e "\nMove sources to target directory /var/www"
    cp -rf /var/www-bak/* /var/www/
fi

echo -e "\nComposer Install"
cd /var/www && composer install
echo -e "\nComposer Update"
cd /var/www && composer update
echo -e "\nLaunch previous entrypoint"
docker-php-entrypoint

echo -e "\nApply Drupal updates"
cd /var/www/web/sites/unapei.fr || exit
/var/www/vendor/drush/drush/drush cr -y
/var/www/vendor/drush/drush/drush updb -y
/var/www/vendor/drush/drush/drush cr -y
/var/www/vendor/drush/drush/drush cim -y
/var/www/vendor/drush/drush/drush cr -y

echo -e "\nLaunch apache"
apache2-foreground
