name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  all:

    runs-on: ubuntu-latest
    
    environment: "CLEYROP DEV"
    
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Add SSH key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/github_actions

    - name: Prepare the environment
      working-directory: scripts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./prepare.sh
        
    - name: Build the image
      working-directory: scripts
      run: |
        ls -al .
        ls -al ../docker/resources
        ./build.sh --no-cache
        
    - name: Test the image
      working-directory: scripts
      run: ./check.sh
        
    - name: Deploy the image
      working-directory: scripts
      run: ./deploy.sh
      if: ${{ github.ref == 'refs/heads/main' }}
        
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
